apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hlaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hlaa
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hlaa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hlaa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hlaa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fbby-tenant/rhtap-demo-app/hacbs-test-project-hlaa@sha256:cadd89fd9d81a7a506643df06ed8845555adb247056caddd8c590992868f2e25
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
