apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hlaa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fbby-tenant/rhtap-demo-app/hacbs-test-project-hlaa@sha256:3c18fb02e1dd68b3a49507b8801ee652614adcdeb2a6f3a1012fdf515c1eee08
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
